[build]
  base    = "exampleSite"
  publish = "exampleSite/public"
  command = "hugo -t repo"

[context.production.environment]
  HUGO_VERSION = "0.45.1"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -tag repo --debug"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.44"

[context.branch-deploy]
  command = "ls -la; hugo -t repo"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.45.1"
