[build]
  base    = "exampleSite"
  publish = "exampleSite/public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.45.1"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.45.1"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.45.1"
